#!/usr/bin/env bash

source setenv.sh

echo "Subindo o ${APP_NAME}..."
docker run -d --name ${APP_NAME}  \
-e OPENSHIFT_URL=${OPENSHIFT_URL} \
-e OPENSHIFT_USERNAME=${OPENSHIFT_USERNAME} \
-e OPENSHIFT_PASSWORD=${OPENSHIFT_PASSWORD} \
-e GITLAB_PRIVATE_KEY=${GITLAB_PRIVATE_KEY} \
-e GITLAB_PROJECT_ID=${GITLAB_PROJECT_ID} \
-e GIT_URL=${GIT_URL} \
-e GIT_REPOSITORIO=${GIT_REPOSITORIO} \
-e GIT_BRANCH=${GIT_BRANCH} \
-e GIT_USERNAME=${GIT_USERNAME} \
-e GIT_PASSWORD=${GIT_PASSWORD} \
-e RECURSOS_FILE=${RECURSOS_FILE} \
-e LOG_DEBUG=${LOG_DEBUG} \
-e EXECUCAO_ATIVADA=${EXECUCAO_ATIVADA} \
-e TZ=America/Sao_Paulo \
${DOCKER_REGISTRY}/${APP_NAME}:${DOCKER_TAG}

# Listando os containers
docker ps